name: sphinx-template

channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - sphinx<7
  - pygments_anyscript
  - myst-parser
  - furo
  - sphinx-copybutton
  - linkify-it-py
  - pyyaml
  - pydata-sphinx-theme
  - sphinx-design
  - sphinx-book-theme
