name: sphinx

channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - sphinx<6
  - pygments_anyscript
  - myst-parser
  - furo
  - sphinx-copybutton
  - linkify-it-py
  - pyyaml
  - pydata-sphinx-theme>=0.10.1
  - pip:
    - git+https://github.com/executablebooks/sphinx-design.git@main
    - git+https://github.com/choldgraf/sphinx-book-theme@jquery
