
trigger: none


pool:
  name: build
  demands:
  - agent.ComputerName -equals ABT-BUILD1

jobs:
- job: build

  steps:
  - checkout: self

  - pwsh: | 
      iwr -useb https://pixi.sh/install.ps1 | iex
      Write-Host "##vso[task.prependpath]$env:USERPROFILE/.pixi/bin"
    displayName: Install pixi

  - pwsh: |
      pixi install
    displayName: Install/update conda env

  - pwsh: pixi run sphinx-build -M html Docs/. Docs/_build -W --keep-going
    displayName: Build sphinx page

  - pwsh: pixi run sphinx-build -M linkcheck Docs/. Docs/_build
    displayName: Sphinx Link check


  # - task: CopyFiles@2
  #   displayName: Copy build documentation
  #   inputs:
  #     SourceFolder: Docs/_build/html
  #     Contents: '*'
  #     targetFolder: F:\SphinxBuilds\$(Build.Repository.Name)
  #     overWrite: true
  #     ignoreMakeDirErrors: true

