
name: Build sphinx page

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: prefix-dev/setup-pixi@v0.4.1
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      # Linux and macOS
      - name: Build sphinx page
        run: pixi run sphinx-build -M html Docs/. Docs/_build -W --keep-going

      - name: Link check
        run: pixi run sphinx-build -M linkcheck Docs/. Docs/_build
          
      - name: upload artifact 🚀
        uses: actions/upload-pages-artifact@main
        with:
          path: Docs/_build/html/

  deploy: 
    needs: build
    if: 1 # GitHub pages must be enabled
    permissions:
      pages: write    
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
